spring:
  datasource:
    url: jdbc:h2:mem:postgresqldb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL95Dialect